server:
  port: 8088

logging:
  config: classpath:logback-spring.xml

spring:
  datasource:
    name: test
    url: jdbc:mysql://101.132.154.224:3306/demo
    username: root
    password: 890828
    driver-class-name: com.mysql.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mapper/*.xml

  mvc:
    view:
      prefix: /
      suffix: .jsp

