server:
  port: 8088

logging:
  config: classpath:logback-spring.xml

spring:
  datasource:
    name: test
    url: jdbc:mysql://101.132.154.224:3306/demo
    username: root
    password: 890828
    driver-class-name: com.mysql.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mapper/*.xml

  mvc:
    view:
      prefix: /
      suffix: .jsp

eureka:
  client:
    service-url:
      defaultZone: http://101.132.154.224:9500/eureka/

xxl:
  job:
    admin:
      addresses: http://101.132.154.224:9600/xxl-job-admin/
    executor:
      appname: xxl-job-executor-demo
      ip:
      port: 33066
      logpath: /opt/logs/demo/jobhandler
      logretentiondays: -1
    accessToken:

